### ISSUE TITLE
AppSettings Widget just opens a new map

### ISSUE THREAD

**Issue by JMaps88** [roemhildtg/cmv-widgets#44]
Hi,

I have been trying to get the AppSettings widget working with the end goal of allowing my end users to have a way to open there map up on a new terminal and continue where they left off, this includes basemap selected, map extent and graphics drawn with the draw widget. I was hoping your widget would allow me to do this or at least be a good starting point, however all it seems to do at the moment is show the "Share Map" popup and then proceed to open a new map when you click "Share This Map".

Obviously I'm missing something as the map that it opens is a blank map without any of the users settings saved.

Any help you could provide would be greatly appreciated.

**Comment by roemhildtg** [comment]
A few notes 

 - App settings doesn't currently handle drawings or basemap. You can implement this using the directions in the readme though, but it involves serializing your drawings to JSON and then re-creating them once app settings loads. 

- Share this map creates a link that you can share with others so that they might be able to open the map up at the location with the visible layers you can see. 

 - App settings uses local storage to persist map data for each user. So if the user switches to a different computer, they'll need a link that was generated using the share this map button. 

Hope that helps answer your questions a bit.

**Comment by JMaps88** [comment]
Ok so I must be missing something because it so far it doesn’t share any settings, like layers turned on or off etc.
